name: Check Label Documentation

on:
  pull_request:
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MDBOOK_VERSION: 0.4.37 # https://github.com/rust-lang/mdBook/releases
      TERA_VERSION: 0.2.4 # https://github.com/chevdor/tera-cli/release

    steps:
      - name: Checkout sources
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          fetch-depth: 0

      - name: Install Tools
        run: |
          wget -O ${{ runner.temp }}/mdbook.tar.gz https://github.com/rust-lang/mdBook/releases/download/v${MDBOOK_VERSION}/mdbook-v${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz && \
          tar xf ${{ runner.temp }}/mdbook.tar.gz && mv mdbook /usr/local/bin && \
          wget -O ${{ runner.temp }}/tera.deb https://github.com/chevdor/tera-cli/releases/download/v${TERA_VERSION}/tera-cli_linux_amd64.deb && \
          sudo dpkg -i ${{ runner.temp }}/tera.deb

      - name: Generate the doc
        run: ./scripts/build-doc.sh

      - name: Check
        run: ls -al ./docs/src

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - name: Render book
        run: ./scripts/generate_book.sh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: ./docs/book
