name: Check label Rules

on:
  push:
    branches: [main]
  pull_request:

env:
  IMAGE: paritytech/ruled_labels:0.4.0

jobs:
  check-label-rules:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [polkadot-sdk]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Pull image
        run: docker pull $IMAGE

      - name: Check label Rules for ${{ matrix.repo }}
        env:
          MOUNT: /work
          RULES_PATH: ruled_labels
        run: |
          docker run --rm -i -v $PWD/${RULES_PATH}/:$MOUNT $IMAGE test -s ${MOUNT}/specs_${{ matrix.repo }}.yaml ${MOUNT}/tests_${{ matrix.repo }}.yaml
