name: Generate Label Documentation

on:
  pull_request:

jobs:
  check-label-rules:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [polkadot, cumulus]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Install tooling
        run: |
          URL=https://github.com/chevdor/tera-cli/releases/download/v0.2.3/tera-cli_linux_amd64.deb
          wget $URL -O tera.deb
          sudo dpkg -i tera.deb
          tera --version

      - name: Check label Rules ${{ matrix.repo }}
        run: |
          export DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          export COMMIT=$(git rev-parse HEAD)
          tera --env --env-key env --template templates/template.md.tera ruled_labels/specs_${{ matrix.repo }}.yaml > ./docs/${{ matrix.repo }}.md

      - name: Update doc
        run: |
          git config --global user.name 'TeraBot'
          git config --global user.email 'chevdor@users.noreply.github.com'
          git config --global push.default current
          git commit docs/* -m "Update label documentation"
          git push
